name: Deploy on K8S Cluster

on:
  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed
  
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Update image tag in deployment YAML
        run: |
          sed -i "s|image:.*|image: ${{ vars.DOCKER_REPOSITORY }}/${{ vars.DOCKER_PROJECT_NAME }}:${{ github.sha }}|g" .github/workflows/yaml/my-portfolio-deploy.yaml
      
      - name: Create Docker registry secret
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: delete secret regcred --ignore-not-found=true
      
      - name: Create new Docker registry secret
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=${{ secrets.DOCKER_USERNAME }} --docker-password=${{ secrets.DOCKER_PASSWORD }}
      
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f .github/workflows/yaml/my-portfolio-deploy.yaml
      
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          binaries-url: "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" # specify the download url explicitly
          command: rollout status deployment/my-portfolio