name: Deploy on K8S Cluster

on:
  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed
  
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Update image tag in deployment YAML
        run: |
          sed -i "s|image:.*|image: ${{ vars.DOCKER_REPOSITORY }}/${{ vars.DOCKER_PROJECT_NAME }}:${{ github.sha }}|g" .github/workflows/yaml/my-portfolio-deploy.yaml
      
      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
      
      - name: Create Docker registry secret
        run: |
          kubectl delete secret regcred --ignore-not-found=true
          kubectl create secret docker-registry regcred \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username="${{ secrets.DOCKER_USERNAME }}" \
            --docker-password="${{ secrets.DOCKER_PASSWORD }}" \
            --docker-email="${{ secrets.DOCKER_EMAIL }}"
      
      - name: Save current deployment for rollback
        run: |
          kubectl get deployment my-portfolio-deployment -o yaml > /tmp/previous-deployment.yaml || echo "No previous deployment found"
      
      - name: deploy to cluster
        id: deploy
        run: kubectl apply -f .github/workflows/yaml/my-portfolio-deploy.yaml
      
      - name: verify deployment
        id: verify
        run: |
          kubectl rollout status deployment/my-portfolio-deployment --timeout=5m
        continue-on-error: true
      
      - name: Rollback on failure
        if: steps.verify.outcome == 'failure'
        run: |
          echo "Deployment verification failed. Rolling back..."
          if [ -f /tmp/previous-deployment.yaml ]; then
            kubectl apply -f /tmp/previous-deployment.yaml
            kubectl rollout status deployment/my-portfolio-deployment --timeout=5m
            echo "Rollback completed successfully"
          else
            kubectl rollout undo deployment/my-portfolio-deployment
            echo "Rolled back using kubectl undo"
          fi
          exit 1